### ISSUE TITLE
Agregar carga de campos automáticos al seleccionar un detalle

### ISSUE THREAD

**Issue by Bridua98** [Bridua98/AgriDjo#3]
(Ej: Precio e %IVA al seleccionar items en venta)

**Comment by toviaferna** [comment]
A parte de ventas cuales serian ?

**Comment by Bridua98** [comment]
Compra, Actividad Agrícola Nota Debito Nota Crédito

**Comment by Bridua98** [comment]
Agregar a los siguientes formularios.
Actividad agrícola: 
- Ítems (% Impuesto y Costo) 
-Maquinarias (precio HA)
Notas de Débito y Crédito (Emitidas y Recibidas)
- Ítems (% Impuesto y costo/precio)

**Comment by Bridua98** [comment]
Culminado

**Comment by Bridua98** [comment]
cerrado
